name: flutter_pptx
description: A package for creating pptx files from markdown, widgets or slide templates.
version: 0.1.2+1
repository: https://github.com/rodydavis/flutter_pptx
homepage: https://github.com/rodydavis/flutter_pptx

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

funding:
  - https://www.buymeacoffee.com/rodydavis
  - https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=WSH3GVC49GNNJ

dependencies:
  flutter:
    sdk: flutter
  dart_pptx: ^0.1.2+1
  screenshot: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
